# Generated by Django 5.1.2 on 2024-10-24 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nabeel', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='search',
            options={'ordering': ('created_at',)},
        ),
    ]
