# Generated by Django 5.1.2 on 2024-10-24 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nabeel', '0002_alter_search_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='search',
            options={},
        ),
    ]
