# Generated by Django 5.1.2 on 2024-10-25 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('time', models.DateField(auto_now_add=True)),
                ('comment', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TempatKuliner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('alamat', models.CharField(max_length=255)),
                ('longitude', models.CharField(max_length=255)),
                ('latitude', models.CharField(max_length=255)),
                ('jamBuka', models.DateTimeField()),
                ('jamTutup', models.DateTimeField()),
                ('rating', models.IntegerField()),
                ('foto_link', models.TextField()),
                ('variasi', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Makanan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('harga', models.IntegerField()),
                ('foto_link', models.TextField()),
                ('tempat_kuliner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='makanan', to='zoya.tempatkuliner')),
            ],
        ),
    ]
