# Generated by Django 5.1.1 on 2024-10-23 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoya', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Makanan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('harga', models.IntegerField()),
                ('foto', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='TempatKuliner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('alamat', models.CharField(max_length=255)),
                ('longitude', models.CharField(max_length=255)),
                ('latitude', models.CharField(max_length=255)),
                ('jamBuka', models.DateTimeField()),
                ('jamTutup', models.DateTimeField()),
                ('rating', models.IntegerField()),
                ('foto', models.ImageField(upload_to='')),
            ],
        ),
    ]
