# Generated by Django 5.1.2 on 2024-10-25 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoya', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='makanan',
            name='foto_link',
            field=models.TextField(default='https://cdn.britannica.com/36/123536-050-95CB0C6E/Variety-fruits-vegetables.jpg'),
        ),
        migrations.AlterField(
            model_name='tempatkuliner',
            name='foto_link',
            field=models.TextField(default='https://cdn.britannica.com/36/123536-050-95CB0C6E/Variety-fruits-vegetables.jpg'),
        ),
    ]
