# Generated by Django 5.1.1 on 2024-10-26 09:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoya', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communityforum',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
