# Generated by Django 5.1.1 on 2024-10-23 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoya', '0002_makanan_tempatkuliner'),
    ]

    operations = [
        migrations.AddField(
            model_name='makanan',
            name='tempat_kuliner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='makanan', to='zoya.tempatkuliner'),
        ),
        migrations.AddField(
            model_name='tempatkuliner',
            name='variasi',
            field=models.CharField(default='', max_length=255),
        ),
    ]
