# Generated by Django 5.1.1 on 2024-10-26 17:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoya', '0002_alter_communityforum_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='makanan',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
