# Generated by Django 5.1.2 on 2024-10-26 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoya', '0002_alter_communityforum_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempatkuliner',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='variasi',
            name='nama',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
