# Generated by Django 5.1.1 on 2024-10-25 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoya', '0004_communityforum_delete_communityform_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tempatkuliner',
            name='variasi',
        ),
        migrations.CreateModel(
            name='Variasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('tempat_kuliner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variasi', to='zoya.tempatkuliner')),
            ],
        ),
    ]
