# Generated by Django 5.1.2 on 2024-10-26 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zoya', '0004_alter_tempatkuliner_rating'),
        ('zoya', '0004_communityforum_delete_communityform_and_more'),
    ]

    operations = [
    ]
