# Generated by Django 5.1.2 on 2024-10-26 04:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoya', '0005_remove_tempatkuliner_variasi_variasi'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempatkuliner',
            name='variasi',
            field=models.ManyToManyField(related_name='tempat_kuliner_set', to='zoya.variasi'),
        ),
        migrations.AlterField(
            model_name='variasi',
            name='tempat_kuliner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variasi_items', to='zoya.tempatkuliner'),
        ),
    ]
