# Generated by Django 5.1.2 on 2024-10-26 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoya', '0006_tempatkuliner_variasi_alter_variasi_tempat_kuliner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tempatkuliner',
            name='variasi',
        ),
        migrations.AlterField(
            model_name='variasi',
            name='tempat_kuliner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variasi', to='zoya.tempatkuliner'),
        ),
    ]
