# Generated by Django 5.1.2 on 2024-10-26 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoya', '0007_remove_tempatkuliner_variasi_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variasi',
            name='tempat_kuliner',
        ),
        migrations.AddField(
            model_name='tempatkuliner',
            name='variasi',
            field=models.ManyToManyField(related_name='tempat_kuliner_set', to='zoya.variasi'),
        ),
    ]
