# Generated by Django 5.1.2 on 2024-10-26 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoya', '0008_remove_variasi_tempat_kuliner_tempatkuliner_variasi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempatkuliner',
            name='jamBuka',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='tempatkuliner',
            name='jamTutup',
            field=models.TimeField(),
        ),
    ]
