# Generated by Django 5.1.2 on 2024-10-25 16:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('zoya', '0002_alter_makanan_foto_link_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('jarak', models.IntegerField()),
                ('makanan', models.ManyToManyField(to='zoya.makanan')),
                ('tempat_kuliner', models.ManyToManyField(to='zoya.tempatkuliner')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
