# Generated by Django 5.1.2 on 2024-10-25 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reksa', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodplan',
            name='description',
        ),
    ]
