# Generated by Django 5.1.2 on 2024-10-25 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
        ('zoya', '0003_makanan_tempat_kuliner_tempatkuliner_variasi'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='tempat_kuliner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='zoya.tempatkuliner'),
        ),
    ]
